### PR TITLE
Fixed #58 - builder should be passed to nested call.

### LINKED ISSUE #58: get_fixtures method ignores passed builder instances
FixtureManager's `get_fixtures` method accepts the builder instance but does not pass it further in nested call to `get_fixture` method.

### PR DESCRIPTION
**Pull request by andrewnester**
Fix for #58

### CODE REVIEW

**Comment by andrewnester** [comment]
I guess it would be also nice to add tests.

**Comment by andrewnester** [comment]
@charlax could you please check this PR? Thanks!

**Comment by andrewnester** [comment]
@erikformella @charlax any updates? or project is dead?

**Comment by charlax** [comment]
Thanks! Indeed this repo is not maintained anymore, but I'll merge your request.

**Comment by andrewnester** [comment]
@charlax thanks!

**Pull request merged**
